### ISSUE TITLE
Document Library - No longer can Rename (or fix typos), Move or Delete file from drop down box

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#147]
When right clicking on a filename a drop down box appears that permits Renaming, Moving or Deleting the file in question. No longer works! Instead a windows box appears that, in part, shows:
Open Link in New Tab
Open Link in New Window
Open Link in Private Window
Bookmark This Link
etc
etc
etc
Can't screen capture this because it disappears which invoking the screen capture program.
Not being able to have Rename or Move is a show stopper for me. Would be nice to keep the Delete feature there as well.

**Comment by josephr5000** [comment]
I'm setting lower priority as the functionality is readily available, albeit mildly less convenient to access.  There are other issues in the queue that will have a much bigger impact if fixed first.

**Comment by TomOwens5000** [comment]
I would like to place a MUST on this one. The "right click" functionality not longer working precludes me from renaming something. This should work like it does in the current production version.

**Comment by TomOwens5000** [comment]
Would sure like to move this one up the pecking order for the LIVE site. Once it is fixed the Document Library will be back to operating normally and I will be able to make the tweaking I need to make for it for our Conference manual.
Tom

**Comment by josephr5000** [comment]
FIXED

Works a little differently than the old site, but hopefully you'll find it pretty clear.

I changed the implementation because the plugin that gave me the right-click menu was misbehaving and proving too time-consuming to find out why it was unhappy, so I chose a different way to offer you a solution.

**Comment by TomOwens5000** [comment]
Almost there.
Can move into a file folder but CANNOT move out of a file folder into just a listing of files that ARE NOT in a file folder.

**Comment by josephr5000** [comment]
Okay, I got the right-click menu working again.  Now that we have a lot more conferences LIVE, I'd like to verify this on TEST before deploying it so would you please check it out on the TEST site and let me know?  Thanks.

**Comment by TomOwens5000** [comment]
Don't move it over yet.

Still some issues. Initial fix works but now there are some error 
messages that come up.

Tried on Karie's windows 10 machine and got some realy distressing 
results that I believe are a result of Windows 10.

My main machine is tied up in a ham radio contest. Will be free later 
tonight. I will get some screen captures then and send them to you --- 
along with more detail explanation of what is going on.

Tom

Will need to document this stuff

**Comment by TomOwens5000** [comment]
Still not ready for prime time.
Yes, I can move and rename directories and files.
When clicking on any stand-alone file (those not in a directory) to see its contents I get the following error message.
![capture](https://cloud.githubusercontent.com/assets/20777996/20655026/6bb81ae2-b4d3-11e6-8f21-fbf3643884f7.JPG)
When uploading a new file from the computer... selecting it invokes the Microsoft Word drop-down box that permits opening or saving the file. That too works correctly and as expected. But trying to read a file that is already in the documents library produces the error above.

As always, the File Folders are sorted alphabetically as new ones are added. Also as before, new files are sorted based on when they are added to the list (last in, first out --- I think). Sure would like to see the sorting routine I suggested for those file but guess that might not happen until 2017.

Another issue for Windows 10 users. This is going to be VERY CONFUSING for our users.
![capture](https://cloud.githubusercontent.com/assets/20777996/20655523/2d0af058-b4d8-11e6-9a60-36c68b52ee65.PNG)

To view a document you have to click on Save or Save As.
Please check this out on Windows 10 to see what can be done about this.
Tom

**Comment by josephr5000** [comment]
Trying to understand your response, Tom.

"Yes, I can move and rename directories and files" -- great!  That's what this fix is all about.  Sounds like you're saying it works as expected.

"When clicking on any standalone file" -- I have done lots of updates that have broken the link between OLD files in the index that you're seeing and files actually stored on the server.  It's not surprising to me that lots of OLD links are broken as you saw.  This has nothing whatsoever to do with the popup menu and renaming, moving and deleting.

"Another issue for Windows 10 users" -- I don't know what file that item is located in, so I couldn't check your file.  I did upload a docx file, and tried downloading it with Edge on Windows 10 and got exactly the same dialog you report.  I tried the same thing on the old site, with exactly the same result, so it's not a new issue and again, has nothing to do with the subject of this issue.  If this is a concern please open a separate issue, and clarify why it's MORE of a concern now than it was on the old site.

**So... the question here is this: did the rename/move/delete fix that I did work right?**

If there are unrelated issues that you notice, please open separate bugs on those.

**Comment by TomOwens5000** [comment]
NO! *NOT AS EXPECTED!*

You can rename and move files.
For example, move a standalone file in the root directory into a file 
folder. Then try to move it back from the file folder into the root 
directory.

My expectation is that it will then be in the root directory. It is not! 
You have to go out into the Main Page and then back into the Document 
Library before the change is visible. It is not being refreshed 
immediately after the change. This is NOT how it works in the OLG site.

As to the WIndows 10 issue ... I had never looked at the database on the 
OLD site, TEST site, or LIVE site so I can't speak as to whether or not 
it is an issue on both sites as you indicate. If it is THAT IS A BIG 
CONCERN AND NEEDS TO BE ADDRESSED. OTHERWISE IT IS GOING TO RESULT IN A 
LOT OF FRUSTRATION AND QUESTIONS BY *ALL *USER OF THE DATABASE, NOT JUST 
OUR CONFERENCE.

I WILL HAVE TO PUT ALL 3 SITES ON KARIE'S WINDOWS 10 MACHINE AND RETEST 
THE WINDOWS 10 ISSUE THERE --- AND THEN WILL FILE A SEPARATE BUG REPORT 
ON THE ISSUE TRACKER BASED ON WHAT I FIND OUT.

**Comment by josephr5000** [comment]
Tried to repro your issue moving file from root to subfolder, then back to root.  Works fine for me.  After the move I'm left looking at the subfolder which no longer contains the file (as expected), and then if I click on root to go to the root folder I see it listed.  What am I missing?

Regarding the ALL CAPS, Tom, you don't need to shout.  I'm just saying it's a separate issue so please file a separate bug so this topic we're discussing doesn't get too confused.
