### ISSUE TITLE
Improve Note formatting

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#265]
From TomO in #217:

Make "Edit | Delete" links on notes blue so they're not so obscure. His initial usability testing with his confernce members suggested they misunderstood yellow to be greyed.

Make "Add Note | Close Request" links bold so they stand out as the more desirable links to use

**Comment by josephr5000** [comment]
FIXED

**Comment by TomOwens5000** [comment]
Just tested again.

Make "Edit | Delete" links on notes blue so they're not so obscure. His initial usability testing with his confernce members suggested they misunderstood yellow to be greyed.

Make "Add Note | Close Request" links bold so they stand out as the more desirable links to use

Neither of these are fixed. Maybe there is a bug but they still do not appear as agreed upon.

**Comment by josephr5000** [comment]
Make sure you press refresh.  If problems persist, give me more detail about what browser you're using, and please try different browsers to see if you get different results.

**Comment by TomOwens5000** [comment]
Ok, tested on Chrome, Firefox and Explorer.
Clicked on Refresh and they all work as expected.
Not sure why I had to click on refresh as I had come in on a fresh log in each time.
An any case, I am closing now. Thanks.
