### ISSUE TITLE
Treasury Payment paid twice

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#267]
I added a request and then closed it with a pledge. I then assigned myself as the Treasurer. I then when in an added the payment to the closed record. I don't know if I hit something twice but it payed it twice. I went in to see if I could duplicate it, but I can no longer create new requests. I set myself back as President and someone else as the Treasurer, logged out and logged back in but I still can't create a request, but I could go edit the payment record. 
The request was for Billy Goat in the Holy Rosary Conference.
This may be two bugs or it may be none. If I need to write another I will.

**Comment by josephr5000** [comment]
When you say you can't create a request, can you be more explicit?  What are you trying?  What happens?  Thanks.

**Comment by DaveSherwood** [comment]
When I click on the Create new Request button, nothing happens.

**Comment by josephr5000** [comment]
I think this is related to #268 which I just fixed.  Could you please try again?

**Comment by DaveSherwood** [comment]
I logged off and logged back in and opened the client record and tried to add a new request but nothing happens when I click the button.

**Comment by josephr5000** [comment]
Be sure to press refresh to encourage your browser to download the fixed javascript.

**Comment by DaveSherwood** [comment]
I restarted my laptop. I still can't create a new request for poor Billy Goat. 

----- Original Message -----

**Comment by josephr5000** [comment]
Dave, restarting isn't guaranteed to get the browser to reload the fixed script file.  You'd need to press F5 (Windows) or Cmd-R (Mac).  Could you please try that?

**Comment by DaveSherwood** [comment]
I can now create new requests.

**Comment by DaveSherwood** [comment]
I have just payed a pledge for Mr Goat and this time it only created one payment. I am not sure how I recorded two payments last time. Should we call this settled and close it? Dave

**Comment by josephr5000** [comment]
Yes, and thanks.
